dvd_rental:
  outputs:
    prod:
      type: snowflake
      threads: 1
      account: VRB60986
      user: AIRBYTE_USER
      password: airbyte_dvd1
      role:  AIRBYTE_ROLE
      warehouse:  PROJECT_TWO
      database: DVD_Rental
      schema: RAW
  target: prod